sudo: required
services:
  - docker

before_install:
  - docker build -t lyndonoc/jmt-backend -f ./JMT-Backend/Dockerfile ./JMT-Backend

script:
  - docker run lyndonoc/jmt-backend npm run test

after_success:
  - docker build -t lyndonoc/jmt-backend -f ./JMT-Backend/Dockerfile ./JMT-Backend
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - docker push lyndonoc/jmt-backend

before_deploy:
  - cd ./JMT-Frontend && npm install && npm run build && cd ../

deploy:
  - provider: s3
    access_key_id:
      secure: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
    bucket: "jmt-client"
    acl: public_read
    skip_cleanup: true
    local_dir: "./JMT-Frontend/dist"
    region: us-east-1
    on:
      all_branches: true
  - provider: elasticbeanstalk
    access_key_id:
      secure: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
    region: "us-east-2"
    app: "JMT-elastic"
    env: "JmtElastic-env"
    bucket_name: "elasticbeanstalk-us-east-2-762560686208"
    bucket_path: "JMT-elastic"
    on:
      all_branches: true
