branch-defaults:
  master:
    environment: JmtElastic-env
environment-defaults:
  JmtElastic-env:
    branch: null
    repository: null
global:
  application_name: JMT-elastic
  default_ec2_keyname: null
  default_platform: docker
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: jmt
  sc: git
  workspace_type: Application
